### ISSUE TITLE
books page is in: optimize loading pane

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#134] opened 2018-10-26 19:26 UTC
## Overview

see comment and screenshot here: [UX: 'This page is in books' loading message in blank pane looks like a bug](https://github.com/Connexions/webview/issues/1620#issuecomment-378671141)

do we want the Books pane to be default closed while it's loading the books list?## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by edwoodward** [comment] 2019-02-01 18:34
I could not reproduce the issue, so I am closing. The books pane loads very fast.

**Closed by edwoodward** 2019-02-01 18:34 UTC
Labels: accepted.bugs&change.requests
