### ISSUE TITLE
SEO: "Books Page Is In" pane should always put the canonical book at the top of the list

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx#206] opened 2018-12-07 23:07 UTC
##Overview
I _think_ the "Books this page is in" pane currently lists the first book the page was published in first.  However, in cases where we've determined that is **not** the canonical book, it should put the canonical book first in the list.  

This was Ross's suggestion; he could provide more information.

## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by Bkblodget** [comment] 2019-01-04 21:07
closing - duplicate of #197

**Closed by Bkblodget** 2019-01-04 21:07 UTC
Labels: seo
