### ISSUE TITLE
PURGE on rebake

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx#16] opened 2018-08-28 14:42 UTC
#Description
As part of the rebaking process we should be purging the cache. Since this isn't on production yet, we simply restart the server-side caching process (varnish), but we will not want to do this in production, if for some reason, we are required to rebake content for a book.

# Solution

As part of the rebaking route on publishing (i.e. `/contents/{ident_hash}/collate-content`) we should make `PURGE` requests to varnish. For those that aren't familiar with the HTTP `PURGE` method, it is used to clear the cache with precision. For example, `PURGE /contents/ace2ec2d-778e-44aa-82c2-57a4e5c3de69@7.16.json` would remove the cache for this books json. We should use the `PURGE` method on all parts of the previously baked book to ensure that the server-side cache is responding with the newly baked book's data.

#Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurence**: [ ] High [ ] Medium  [ ] Low

#Related Issue: 
https://github.com/Connexions/cnx-deploy/issues/129

#Acceptance

**Comment by brittweinstein** [comment] 2018-08-28 14:42
Per Ross on 4/12/2018: "Not sure why this is in bakedPDF - it applies to existing baking primiarly (it's likely that the baking PDF pipeline will access the DB directly, so not have any issues with cache anyway). The problem will be triggered by release of new recipes, which will trigger a rebake of published books that use that recipe , and are currently long-cached in varnish. Workaround for now would be to republish any impacted books."

**Comment by Bkblodget** [comment] 2019-03-08 20:47
duplicate of https://github.com/openstax/cnx/issues/57

closing

**Closed by Bkblodget** 2019-03-08 20:47 UTC
