### ISSUE TITLE
Nebuchadnezzar transformed CNXML to HTML is missing metadata

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx#256] opened 2019-03-05 23:04 UTC
### Description

The results of `neb cnxml-to-html ...` are producing transformed content, but the metadata is missing from the resulting files. This metadata is needed to produce a valid single-html according to `cnx-epub-validate`.

hélène reported a preliminary problem with the assembled single-html:
> `cnx-epub-validate`  failed: `ValueError: A value for 'license_url' could not be found.` The baked looks broken, especially the toc .

----------------
**Steps to Reproduce the bug or Details about Change:** 

There is no straight forward way to reproduce this using the current interface without using the python interpreter directly. The developers are mostly aware of how to go about reproducing this.

Reproduction in the future would involve:
1. `neb get ...`
2. `neb cnxml-to-html ...`
3. `neb assemble ...`
Where the results of step 3 produce an invalid cnx-epub single-html file.

**Comment by pumazi** [comment] 2019-03-06 06:25
@helenemccarron, do Content Managers and/or Text Book Devs **use the metadata in the html**? I'd hate to break what little validation we have. But at the same time, if you aren't using it, what's the point?

**Comment by pumazi** [comment] 2019-03-06 15:10
We do need at least one or two elements of the metadata for deconstruction of the single-page-html. Those two known elements are the id and version. We likely don't need that information for the nebuchadnezzar use-case (short-term need/req).

Deviating from what released baking code does might help in the short-term, but likely will be detrimental in the mid to long term. This code is already somewhat fragmented. I'm concerned that targeting the short-term fix is only going to come back to bite us either as we are developing this or when we get to working on the server-side portion of BakedPDF.

**Comment by Bkblodget** [comment] 2019-03-06 15:27
@pumazi what do you mean by *metadata on html* - is that the same as the collection metadata on legacy?

**Comment by pumazi** [comment] 2019-03-06 15:35
@Bkblodget, the metadata (license, authors, keywords, etc.) I'm speaking of is synonymous with the metadata section in a cnxml/collxml document. In the *internal epub* (used in baking), we put this information in `<div data-type="metadata">...</div>` within the `<body>` of the html content. You can see an example of this at [cnx-epub's fig-bush.html test document](https://github.com/openstax/cnx-epub/blob/master/cnxepub/tests/data/loose-pages/content/fig-bush.xhtml#L46-L166).

In baking we use the metadata information when deconstructing the _single-page-html_ back into individual documents for insertion into the database.

**Comment by Bkblodget** [comment] 2019-03-06 15:40
@pumazi Gotcha. So to answer your question about using metadata in html - yes, the CMs do use this, but currently, due to some confusion about what metadata is actually editable with neb, all metadata edits are made via legacy. - at least I _think_ that answers your question.

**Comment by brittweinstein** [comment] 2019-03-08 19:26
@pumazi since the PR is merged, can we move this to testing?

**Comment by pumazi** [comment] 2019-03-09 00:53
@brittweinstein, one of the PRs is merged. This hasn't fully been addressed yet. The PR you see as merge is in the library package which will be used to support the change in nebuchadnezzar itself. However, as I mentioned in the channel yesterday, there is a small deliverable in `cnxml` v3.0.1. The `extract-cnxml-metadata` script can be used to at least test that part of the work. The other bits of this will be coming along shortly. You can follow that in openstax/nebuchadnezzar#134, which is broader in scope that simply fixing this issue.

**Comment by brittweinstein** [comment] 2019-03-12 15:19
@omehes will you need a test plan or do you have what you need to begin testing this?

**Comment by omehes** [comment] 2019-03-14 17:58
Verified with @helenemccarron by using supplied raw html collection.assembled.xhtml from Michael. No error messages after assemble completion. We found license info in the html and confirmed with @pumazi 
Issue is fixed

**Closed** 2019-03-14 18:05 UTC
Labels: baked-pdf, batch.neb.press, bug
