### ISSUE TITLE
Idea: create a canonical URL on archive that points to the CNX.org version

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#65] opened 2018-10-19 20:00 UTC
##Overview
What does this task accomplish?
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by edwoodward** [comment] 2019-01-31 23:18
Duplicate of https://github.com/openstax/cnx/issues/208. Closing.

**Closed by edwoodward** 2019-01-31 23:18 UTC
Labels: seo
