### ISSUE TITLE
Clean out excessive noise in CNX logs

### ISSUE THREAD

**Issue by ambersdai** [openstax/cnx#141] opened 2018-10-29 18:29 UTC
## Overview
Devops has requested we find a way to clean up the excessive amount of warnings and errors in the CNX logs. Because of the large amount of noise It has been increasingly difficult for them to parse out serious errors that require more attention.

Github issue here: https://app.zenhub.com/workspace/o/connexions/cnx/issues/11

Ross presented an idea to scope the types of errors to help clear the noise. He expressed this would be beneficial as planned work so that in the future he will not be routinely enlisted to stop his work and parse through the errors.

A technical document detailing the scope of errors with input from CNX & Devops is most likely needed.
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
How will QA know this feature works? What parts of regression tests would be most affected?
## Acceptance Criteria
Expected behavior

**Comment by edwoodward** [comment] 2019-02-01 18:48
Duplicate of #11. Closing

**Closed by edwoodward** 2019-02-01 18:48 UTC
Labels: maintenance
